region: us-east-1

function_name: gdoc-dlx
handler: service.handler
description: GDOC to DLX Periodic Task Runner
runtime: python3.8
role: service-role/gdoc-dlx-role-389djnm9

# Build options
build:
  source_directories: lib # a comma delimited list of directories in your project root that contains source to package.
